name: CI

on:
  push:
    branches:
      - main
    path:
      - src/**
      - Cargo.toml
      - Cargo.lock
  pull_request:
    path:
      - src/**
      - Cargo.toml
      - Cargo.lock

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          components: clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-debug-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo clippy --tests --no-deps -- -D warnings

  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          components: rustfmt
      - run: cargo fmt --check

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-debug-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test
